### ISSUE TITLE
Timer and pic dont work anymore

### ISSUE THREAD

**Issue by Logan-Purcell** [niveshbirangal/discord-rpc#1]

**Comment by niveshbirangal** [comment]
@Logan-Purcell It is working. 
![Screenshot 2019-05-03 at 12 57 20 PM](https://user-images.githubusercontent.com/25349137/57124346-14f1d280-6da3-11e9-90b5-c4eb87bd7930.png)

**Comment by niveshbirangal** [comment]
Solved
