### ISSUE TITLE
This is what happens when i run python3 example.py

### ISSUE THREAD

**Issue by deadshot3312** [niveshbirangal/discord-rpc#11]
┌─[deadshot@parrot]─[~/Desktop/discord-rpc]
└──╼ $python3 example.py 
Demo for python-discord-rpc Adobe illustrator
Traceback (most recent call last):
  File "example.py", line 7, in <module>
    rpc_obj = rpc.DiscordIpcClient.for_platform(client_id)  # Send the client ID to the rpc module
  File "/home/deadshot/Desktop/discord-rpc/rpc.py", line 52, in for_platform
    return UnixDiscordIpcClient(client_id)
  File "/home/deadshot/Desktop/discord-rpc/rpc.py", line 44, in __init__
    self._do_handshake()
  File "/home/deadshot/Desktop/discord-rpc/rpc.py", line 59, in _do_handshake
    ret_op, ret_data = self.send_recv({'v': 1, 'client_id': self.client_id}, op=OP_HANDSHAKE)
  File "/home/deadshot/Desktop/discord-rpc/rpc.py", line 107, in send_recv
    self.send(data, op)
  File "/home/deadshot/Desktop/discord-rpc/rpc.py", line 115, in send
    self._write(header)
  File "/home/deadshot/Desktop/discord-rpc/rpc.py", line 200, in _write
    self._sock.sendall(data)
OSError: [Errno 107] Transport endpoint is not connected

**Comment by niveshbirangal** [comment]
did you entred the right client id that was generated in developer settings? 
Also, are u using a desktop app or browser?
Do make sure the RPC file stays with the example in the same directory.

**Comment by deadshot3312** [comment]
> did you entred the right client id that was generated in developer settings?
> Also, are u using a desktop app or browser?
> Do make sure the RPC file stays with the example in the same directory.

The client ID is correct and i am using a desktop app . its a linux os 
i even tried adding "Discord Presence" plugin from vscodium still it shows : Could not connect .

**Comment by deadshot3312** [comment]
> > did you entred the right client id that was generated in developer settings?
> > Also, are u using a desktop app or browser?
> > Do make sure the RPC file stays with the example in the same directory.
> 
> The client ID is correct and i am using a desktop app . its a linux os
> i even tried adding "Discord Presence" plugin from vscodium still it shows : Could not connect .

> 

- [ ] 

- [ ] 

1. 

- [](url)

**Comment by deadshot3312** [comment]
> > did you entred the right client id that was generated in developer settings?
> > Also, are u using a desktop app or browser?
> > Do make sure the RPC file stays with the example in the same directory.
> 
> The client ID is correct and i am using a desktop app . its a linux os
> i even tried adding "Discord Presence" plugin from vscodium still it shows : Could not connect .

t

**Comment by niveshbirangal** [comment]
@deadshot3312 class UnixDiscordIpcClient(DiscordIpcClient) is correct i guess. I will check again in Linux and give you the update. Also if u find some corrections do let me know.

**Comment by D34D-5H07** [comment]
> @deadshot3312 class UnixDiscordIpcClient(DiscordIpcClient) is correct i guess. I will check again in Linux and give you the update. Also if u find some corrections do let me know.

Sorry For the inconvenience . What i did wrong , i installed Discord using Snap . Once i reinstalled the discord from the official website using normal linux way . it worked . Thanks For you Quick reply

**Comment by deadshot3312** [comment]
> @deadshot3312 class UnixDiscordIpcClient(DiscordIpcClient) is correct i guess. I will check again in Linux and give you the update. Also if u find some corrections do let me know.

Sorry For the inconvenience . What i did wrong , i installed Discord using Snap . Once i reinstalled the discord from the official website using normal linux way . it worked . Thanks For you Quick reply

**Comment by Khosraw** [comment]
I have this same issue but I don't use Discord's snap version...

**Comment by niveshbirangal** [comment]
Use the latest version from to official website.

**Comment by Khosraw** [comment]
> Use the latest version from to official website.

I did exactly that

**Comment by Khosraw** [comment]
Nevermind I got it to work... had to reinstall it 2 times and apparently it doesn't work with Discord Development version or Snap.
