### ISSUE TITLE
Playing/watching/streaming

### ISSUE THREAD

**Issue by PblSoftWare** [niveshbirangal/discord-rpc#13]
Well, in the discord-rich presence it usually says: Playing/watching or Streaming. Those are the default ones. How can I change the playing for the watching or streaming?. It is possible to change the playing for another word you want?

**Comment by niveshbirangal** [comment]
Rich Presence was only made for games I guess so we can't do much.

**Comment by PblSoftWare** [comment]
oh, okey yea, I didn't realize that probably your right
