### ISSUE TITLE
not showing up on discord

### ISSUE THREAD

**Issue by tomsdinersys** [niveshbirangal/discord-rpc#19]
I run the program and everything (i use visual studio code) and it says it all was successful, but when i go back to look and see if it's running it's not running at all, it's not showing me playing anything.

discord-rpc % python3 example.py
Demo for python-discord-rpc Adobe illustrator
RPC connection successful.

thats a direct copy-paste from the terminal (excluding my email and such that it gives on the terminal), how do i fix this??

**Comment by tomsdinersys** [comment]
update: I go to the github one and it showed it wasn't fully executed,

**Comment by niveshbirangal** [comment]
Are you using the latest version of discord?

**Comment by omsenjalia** [comment]
Can I host this on reply.it

**Comment by omsenjalia** [comment]
Repl.it

**Comment by niveshbirangal** [comment]
If you want to host I would suggest using "AWS free tire EC2 instance". But I really don't see any use-case for hosting it or running it for long.

**Comment by omsenjalia** [comment]
> If you want to host I would suggest using "AWS free tire EC2 instance". But I really don't see any use-case for hosting it or running it for long.

How

**Comment by omsenjalia** [comment]
Like some other guys say it's not possible

**Comment by omsenjalia** [comment]
Hello?

**Comment by f1bdis** [comment]
@omxpro  it does not depend on what other guys say. If it's possible in your OS then it's possible on AWS. If you know AWS you can easily do it. If you don't then you cant.
