### ISSUE TITLE
OSError

### ISSUE THREAD

**Issue by Kawasofft** [niveshbirangal/discord-rpc#24]
Hello, I'm on a Linux Mint computer, and after all the steps indicated, I have this error that appears: 
![image](https://user-images.githubusercontent.com/85878841/177005367-660ee9b3-2f88-4ce5-b973-1c1172c90fc1.png)
Please, can you help me ?

**Comment by ghost** [comment]
The same trouble ;)

**Comment by niveshbirangal** [comment]
@Kawasofft @devb1t  it doesn't work properly with the Discord Development version or if you have installed it via snap. Reinstall it from the official site.

**Comment by hzswdef** [comment]
@niveshbirangal ok, thx ;)

**Comment by Kawasofft** [comment]
Ok, thx

Le sam. 9 juil. 2022 à 15:28, Nivesh Birangal ***@***.***> a
écrit :
