### ISSUE TITLE
Add buttons

### ISSUE THREAD

**Issue by Impre-visible** [niveshbirangal/discord-rpc#26]
Can you add buttons to the rpc please ?

**Comment by f1bdis** [comment]
I guess you cant implement it in python? @Impre-visible

**Comment by Impre-visible** [comment]
I huess you can 😂 some C# oib can do it, you just have to figured out how to do that

**Comment by f1bdis** [comment]
@Impre-visible okay, looking forward for you or the repo owner implementing it.
