### ISSUE TITLE
Status not showing

### ISSUE THREAD

**Issue by TomDevX** [niveshbirangal/discord-rpc#31]
I did all the steps, and the terminal said that the programme was running, but there's no status in my Discord app.
<img width="1033" alt="image" src="https://github.com/niveshbirangal/discord-rpc/assets/87766694/ab579736-8fb7-4c7e-bc39-9ee29ccf2511">
<img width="355" alt="image" src="https://github.com/niveshbirangal/discord-rpc/assets/87766694/dcb56a3f-56b0-4726-8003-9abfa9da0bff">

**Comment by niveshbirangal** [comment]
Hello, you first need to make application (https://discord.com/developers/applications) then copy application id to the to example.py and then run it.
