### ISSUE TITLE
Randomly crashing because of broken pipe

### ISSUE THREAD

**Issue by MIGI10** [niveshbirangal/discord-rpc#6]
Hi,

I keep getting a [Errno 32] Broken pipe error randomly. The script runs okay but sometimes randomly after some minutes it crashes with this error:

Traceback (most recent call last):
  File "/Users/user/Desktop/folder/folder/script.py", line 27, in <module>
    rpc_obj.set_activity(activity)
  File "/Users/user/Desktop/folder/folder/rpc.py", line 138, in set_activity
    self.send(data)
  File "/Users/user/Desktop/folder/folder/rpc.py", line 116, in send
    self._write(header)
  File "/Users/user/Desktop/folder/folder/rpc.py", line 201, in _write
    self._sock.sendall(data)
BrokenPipeError: [Errno 32] Broken pipe

**Comment by niveshbirangal** [comment]
After how many minutes?
Have you cleared the fields in the developer portal? 
You can write your activity in your script or in the developer portal as it overwrites( not on both )
How many times the did error arrive? Also which OS you are using?
You can check on the beta branch and let me know if this still arrives.

**Comment by MIGI10** [comment]
> After how many minutes?
> Have you cleared the fields in the developer portal?
> You can write your activity in your script or in the developer portal as it overwrites( not on both )
> How many times the did error arrive? Also which OS you are using?
> You can check on the beta branch and let me know if this still arrives.

Sometimes it can be after 5 minutes other times 2 hours...
What do you mean with clear fields in the developer portal?
I get the error like two three times every day and i'm on MacOS Big Sur beta

**Comment by niveshbirangal** [comment]
Ohh. Sorry, I haven't tried out MacOS Big Sur beta. This runs well in all stable versions. 
Clear field means -> when you input your activity in the discord dashboard or in the script. make sure you clear one thing. 
Like if you change values in the script make sure you have cleared the fields in the developer portal.
![fileds](https://user-images.githubusercontent.com/25349137/92866246-f121b080-f41c-11ea-9161-1bcf727e9057.png)

**Comment by subatomic-olive** [comment]
I have this same issue in Catalina.

**Comment by niveshbirangal** [comment]
Hey, @subatomic-olive I'm working on it. Please if you find some solution let me know.

**Comment by subatomic-olive** [comment]
Ok, thanks

**Comment by subatomic-olive** [comment]
It is no longer happening after I cleared the fields and turned on "Display currently running game as status message," which had turned off for some reason. Thanks so much for creating this.

**Comment by subatomic-olive** [comment]
It still returns the errors after the run, though.

**Comment by niveshbirangal** [comment]
@subatomic-olive ohh okay. I will try to fix it. Thanks for trying it.

**Comment by Esdeatho** [comment]
Im still getting this error and the presence won't show up any fixes?

**Comment by niveshbirangal** [comment]
No, I haven't worked on it yet. please do let me know if you find a solution.

**Comment by Esdeatho** [comment]
> No, I haven't worked on it yet. please do let me know if you find a solution.

can I get an estimate of when it will be finished?

**Comment by niveshbirangal** [comment]
This month probably. If I work on it. But there are more RPC you can explore the template will be the same for all.

**Comment by morning-paradigm** [comment]
I've switched Python 3.8 to 3.9 for this script and been using it for some time now with 5-6+ hour sessions and I don't remember encountering this issue ever since. Maybe it's related, maybe I'm just lucky.

**Comment by SetuCoder** [comment]
Please do something to fix this. In my case, it is even faster, I guess within just 15 minutes. This is driving me crazy. I was so happy that I found this one which works, among the other ones. But...

**Comment by niveshbirangal** [comment]
@SetuCoder Which version of python you are using? Also, are you using macOS or another OS?

**Comment by SetuCoder** [comment]
> @SetuCoder Which version of python you are using? Also, are you using macOS or another OS?

I am using macOS Big Sur 11.1 with python 3.9.x (IDK which is the latest but what I'm using is) on MacBook Air 2017.

**Comment by niveshbirangal** [comment]
@MIGI10 @subatomic-olive @esdeatho @SetuCoder
I have fixed the issue let me know if it still comes.
