### ISSUE TITLE
Automatically run the 'game'

### ISSUE THREAD

**Issue by subatomic-olive** [niveshbirangal/discord-rpc#8]
Is there a way to have the status automatically run or run when I have a certain app open so I don't need to keep PyCharm open?

**Comment by niveshbirangal** [comment]
You can use the terminal if you don't want to use PyCharm.
For displaying specific activity you need to run the script. 
If discord supports your app (for example Spotify it will automatically take it and put it in your activity status)

**Comment by subatomic-olive** [comment]
How do I run it with the terminal if I'm using Python 3.9? ```python 3.9 example.py``` doesn't work

**Comment by niveshbirangal** [comment]
Just go to the folder in which example.py is present through the terminal. Then use the command python3 example.py
