### ISSUE TITLE
(not an issue) AdobeXD and AdobeAfterEffects folders

### ISSUE THREAD

**Issue by subatomic-olive** [niveshbirangal/discord-rpc#9]
What are the "AdobeXD" and "AdobeAfterEffects" folders for?

**Comment by niveshbirangal** [comment]
Same as the example, It's basically to show how to implement things. With different profiles.

**Comment by subatomic-olive** [comment]
Are they linked to be displayed when the apps are open?

**Comment by niveshbirangal** [comment]
No! They are like profiles. You can go to the respective folder and run it, It will work (but you have to do the setup in the developer setting)
